<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="2" failed="3" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[status code is =========200expected========200.0]]>
    </line>
    <line>
      <![CDATA[status code is =========502expected========200.0]]>
    </line>
    <line>
      <![CDATA[status code is =========502expected========200.0]]>
    </line>
    <line>
      <![CDATA[status code is =========502expected========200.0]]>
    </line>
  </reporter-output>
  <suite started-at="2023-05-06T14:06:23 IST" name="Default suite" finished-at="2023-05-06T14:06:34 IST" duration-ms="10587">
    <groups>
    </groups>
    <test started-at="2023-05-06T14:06:23 IST" name="Default test" finished-at="2023-05-06T14:06:34 IST" duration-ms="10587">
      <class name="com.w2a.zoho.utilities.FactoApi">
        <test-method signature="LoginjwtToken()[pri:1, instance:com.w2a.zoho.utilities.FactoApi@35e2d654]" started-at="2023-05-06T14:06:23 IST" name="LoginjwtToken" finished-at="2023-05-06T14:06:29 IST" duration-ms="5292" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginjwtToken -->
        <test-method signature="myTest(java.lang.String,java.lang.String,java.lang.String,double)[pri:2, instance:com.w2a.zoho.utilities.FactoApi@35e2d654]" started-at="2023-05-06T14:06:30 IST" name="myTest" data-provider="excelData" finished-at="2023-05-06T14:06:30 IST" duration-ms="595" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[post]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://91fjgvixl9.execute-api.ap-south-1.amazonaws.com/testing/v1/fetchAllClients]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[""]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[200.0]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[status code is =========200expected========200.0]]>
            </line>
          </reporter-output>
        </test-method> <!-- myTest -->
        <test-method signature="myTest(java.lang.String,java.lang.String,java.lang.String,double)[pri:2, instance:com.w2a.zoho.utilities.FactoApi@35e2d654]" started-at="2023-05-06T14:06:30 IST" name="myTest" data-provider="excelData" finished-at="2023-05-06T14:06:31 IST" duration-ms="339" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[post]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://91fjgvixl9.execute-api.ap-south-1.amazonaws.com/testing/v1/insertClients]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[{\r\n"
  + "             \"data\": {\r\n"
  + "                 \"client_name\": \"kavin\",\r\n"
  + "                 \"entity_name\": \"My New Entity3\",\r\n"
  + "                 \"sub_category\": \"My New Subcategory3\",\r\n"
  + "                 \"client_address\": \"My New Address3\",\r\n"
  + "                 \"primary_contact_details\": \"909090909\",\r\n"
  + "                 \"secondary_contact_details\": \"9999999991\",\r\n"
  + "                 \"billing_address\": \"My New Billing Address3\",\r\n"
  + "                 \"sla_agreement\": \"\",\r\n"
  + "                 \"client_components\": [\r\n"
  + "                     \"Address\"\r\n"
  + "                 ],\r\n"
  + "                 \"pricing\": \"900000001\"\r\n"
  + "             }\r\n"
  + "         }]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[200.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [502]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at com.w2a.zoho.utilities.FactoApi.myTest(FactoApi.java:104)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[status code is =========502expected========200.0]]>
            </line>
          </reporter-output>
        </test-method> <!-- myTest -->
        <test-method signature="myTest(java.lang.String,java.lang.String,java.lang.String,double)[pri:2, instance:com.w2a.zoho.utilities.FactoApi@35e2d654]" started-at="2023-05-06T14:06:31 IST" name="myTest" data-provider="excelData" finished-at="2023-05-06T14:06:33 IST" duration-ms="1870" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[post]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://91fjgvixl9.execute-api.ap-south-1.amazonaws.com/testing/v1/updateClient]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[{\r\n"
          + "    \"data\": {\r\n"
          + "        \"client_name\": \"Oracle24356\",\r\n"
          + "        \"entity_name\": \"My New Entity5\",\r\n"
          + "        \"sub_category\": \"My New Subcategory5\",\r\n"
          + "        \"client_address\": \"My New Address5\",\r\n"
          + "        \"primary_contact_details\": \"9090909095\",\r\n"
          + "        \"secondary_contact_details\": \"9999999995\",\r\n"
          + "        \"billing_address\": \"My New Billing Address5\",\r\n"
          + "        \"sla_agreement\": \"pak5.jpg\",\r\n"
          + "        \"client_components\": [\r\n"
          + "            \"Address\",\r\n"
          + "            \"Employment\"\r\n"
          + "        ],\r\n"
          + "        \"pricing\": \"9000000015\",\r\n"
          + "        \"client_id\": \"88ef3ebe-e6fb-5a8a-a192-054b8354af29\"\r\n"
          + "    }\r\n"
          + "}
            ]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[200.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [502]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at com.w2a.zoho.utilities.FactoApi.myTest(FactoApi.java:104)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[status code is =========502expected========200.0]]>
            </line>
          </reporter-output>
        </test-method> <!-- myTest -->
        <test-method signature="myTest(java.lang.String,java.lang.String,java.lang.String,double)[pri:2, instance:com.w2a.zoho.utilities.FactoApi@35e2d654]" started-at="2023-05-06T14:06:33 IST" name="myTest" data-provider="excelData" finished-at="2023-05-06T14:06:34 IST" duration-ms="1421" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[post]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://91fjgvixl9.execute-api.ap-south-1.amazonaws.com/testing/v1/deleteClient]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[{\r\n"
              + "    \"data\":\r\n"
              + "    {\r\n"
              + "         \"client_id\": \"88ef3ebe-e6fb-5a8a-a192-054b8354af29\"\r\n"
              + "    }\r\n"
              + "}]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[200.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [502]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at com.w2a.zoho.utilities.FactoApi.myTest(FactoApi.java:104)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[status code is =========502expected========200.0]]>
            </line>
          </reporter-output>
        </test-method> <!-- myTest -->
      </class> <!-- com.w2a.zoho.utilities.FactoApi -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
